// *********************************************************************************************************************
// Description:		GDL application_query and request fix strings 
//
// Module:			VBElemOperations
// Namespace:
// Contact person:
//
// *********************************************************************************************************************

#ifndef GDLAPPLICATIONQUERYSTRINGS_HPP
#define GDLAPPLICATIONQUERYSTRINGS_HPP

// Application query strings
#define APPQUERY_DOCUMENT_FEATURE								"DOCUMENT_FEATURE"
#define APPQUERY_DOCUMENT_FEATURE_VIEW_DIRECTION				"VIEW_DIRECTION"

#define APPQUERY_PARAMETER_SCRIPT								"PARAMETER_SCRIPT"
#define APPQUERY_PARAMETER_FIRSTOCCASION_IN_PROGRESS			"FIRSTOCCASION_IN_PROGRESS"

#define APPQUERY_MEP_SYSTEM										"MEPSYSTEM"
#define APPQUERY_MEP_SYSTEM_GET_MEP_SYSTEMS						"GETMEPSYSTEMS"
#define APPQUERY_MEP_SYSTEM_GET_DOMAIN							"GETDOMAIN"
#define APPQUERY_MEP_SYSTEM_GET_CONTOUR_PEN						"GETCONTOURPEN"
#define APPQUERY_MEP_SYSTEM_GET_FILL_PEN						"GETFILLPEN"
#define APPQUERY_MEP_SYSTEM_GET_BACKGROUND_PEN					"GETBACKGROUNDPEN"
#define APPQUERY_MEP_SYSTEM_GET_FILL_TYPE						"GETFILLTYPE"
#define APPQUERY_MEP_SYSTEM_GET_CENTERLINE_TYPE					"GETCENTERLINETYPE"
#define APPQUERY_MEP_SYSTEM_GET_CENTERLINE_PEN					"GETCENTERLINEPEN"
#define APPQUERY_MEP_SYSTEM_GET_SYSTEM_MATERIAL					"GETSYSTEMMATERIAL"
#define APPQUERY_MEP_SYSTEM_GET_INSULATION_MATERIAL				"GETINSULATIONMATERIAL"

#define APPQUERY_MEP_MODELER									"MEPMODELER"
#define APPQUERY_MEP_MODELER_IS_AVAILABLE						"ISAVAILABLE"

#define APPQUERY_MEP_CONNECTION_TYPE							"MEPCONNECTIONTYPE"
#define APPQUERY_MEP_CONNECTION_TYPE_GET_CONNECTION_TYPES		"GETCONNECTIONTYPES"
#define APPQUERY_MEP_CONNECTION_TYPE_GET_CONNECTION_TYPE_STYLE	"GETCONNECTIONTYPESTYLE"

#define APPQUERY_MEP_FLEXDUCT									"MEPFLEXIBLESEGMENT"
#define APPQUERY_MEP_FLEXDUCT_START_SECTIONING					"STARTSECTIONING"
#define APPQUERY_MEP_FLEXDUCT_ADD_CONTROL_POINT					"ADDCONTROLPOINT"
#define APPQUERY_MEP_FLEXDUCT_ADD_VECTORS						"ADDDIRECTIONANDWIDTHVECTOR"
#define APPQUERY_MEP_FLEXDUCT_END_SECTIONING					"ENDSECTIONING"

#define APPQUERY_MEP_BEND										"MEPBEND"
#define APPQUERY_MEP_BEND_GET_BEND_TYPE_NAMES					"GETBENDTYPENAMES"

#define APPQUERY_LIBRARY_MANAGER								"LIBRARY_MANAGER"
#define APPQUERY_LIBRARY_MANAGER_IES_FILES						"IES_FILES"
#define APPQUERY_LIBRARY_MANAGER_USER_IMAGE_FILES				"USER_IMAGE_FILES"

// Tags and Categories Parameters
#define APPQUERY_OWNCUSTOMPARAMETERS							"OWNCUSTOMPARAMETERS"
#define APPQUERY_PARENTCUSTOMPARAMETERS							"PARENTCUSTOMPARAMETERS"
#define APPQUERY_GETPARAMETERFOLDERNAMES						"GETPARAMETERFOLDERNAMES"
#define APPQUERY_GETPARAMETERNAMES								"GETPARAMETERNAMES"
#define APPQUERY_GETPARAMETER									"GETPARAMETER"
#define APPQUERY_FOLDERID_MAIN									"Main.Folder"
#define APPQUERY_FOLDERID_RENOVATION							"Renovation.Folder"
#define APPQUERY_FOLDERID_IFCPROPERTIES							"IFC.Folder"

#define APPQUERY_PARAMID_MAIN_ID								"Main.ID"
#define APPQUERY_PARAMID_MAIN_STRUCTURAL						"Main.StructuralFunction"
#define APPQUERY_PARAMID_MAIN_POSITION							"Main.Position"
#define APPQUERY_PARAMID_MAIN_CLASSIFICATION					"Main.ElementClassification"
#define APPQUERY_PARAMID_MAIN_BRICATEGORY						"Main.BRICategory"
#define APPQUERY_PARAMID_RENOVATION_STATUS						"Renovation.RenovationStatus"
#define APPQUERY_PARAMID_RENOVATION_SHOWONRENOFILTER			"Renovation.ShowOnRenovationFilter"

#define APPQUERY_PARAMID_IFC_TYPE								"IFC.Type"
#define APPQUERY_PARAMID_IFC_AC_IFC_ID							"IFC.ArchiCADIFCID"
#define APPQUERY_PARAMID_IFC_EXTERNAL_IFC_ID					"IFC.ExternalIFCID"
#define APPQUERY_PARAMID_IFC_ATTRIBUTE_PREFIX					"IFC.Attributes"
#define APPQUERY_PARAMID_IFC_PSET_PREFIX						"IFC.PSet"
#define APPQUERY_PARAMID_IFC_CLASSREF_PREFIX					"IFC.ClassificationReference"
#define APPQUERY_PARAMID_IFC_SEPARATOR							"."

#define REQUEST_PROPERTIES_IFC_PROPTYPE							"IFC"

#endif