#ifndef BUILTIN_PROFILE_PARAMETER_IDS_HPP
#define	BUILTIN_PROFILE_PARAMETER_IDS_HPP

#pragma once

#include "VectorImageTypedefs.hpp"
#include "VectorImageExport.h"
#include "Array.hpp"

namespace PVI {

VI_DLL_EXPORT extern const ProfileBuiltInParameterId StretchZoneWidthProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId StretchZoneHeightProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId StretchZoneLeftProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId StretchZoneRightProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId StretchZoneBottomProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId StretchZoneTopProfileParameterId;

VI_DLL_EXPORT extern const ProfileBuiltInParameterId TotalWidthProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId TotalHeightProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId TotalLeftProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId TotalRightProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId TotalBottomProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId TotalTopProfileParameterId;

VI_DLL_EXPORT extern const ProfileBuiltInParameterId NominalWidthProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId NominalHeightProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId NominalLeftProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId NominalRightProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId NominalBottomProfileParameterId;
VI_DLL_EXPORT extern const ProfileBuiltInParameterId NominalTopProfileParameterId;

VI_DLL_EXPORT const GS::Array<ProfileBuiltInParameterId>& GetAllBuiltInProfileParameterIDs ();
}

#endif
