#ifndef PROPERTY_OPERATIONS__EXPORT_H
#define PROPERTY_OPERATIONS__EXPORT_H

#pragma once

#include "PlatformDLLExport.hpp"

#if defined (PROPERTY_OPERATIONS_DLL_COMPILE)
	#define PROPERTY_OPERATIONS_DLL_EXPORT		PLATFORM_DLL_EXPORT
#else
	#define PROPERTY_OPERATIONS_DLL_EXPORT		PLATFORM_DLL_IMPORT
#endif

#if defined (PROPERTY_OPERATIONS_DLL_COMPILE)
	#define PROPERTY_OPERATIONS_DLL_EXPORT_FOR_TEST		PLATFORM_DLL_EXPORT
#elif defined (PROPERTY_OPERATIONS_TEST_DLL_COMPILE)
	#define PROPERTY_OPERATIONS_DLL_EXPORT_FOR_TEST		PLATFORM_DLL_IMPORT
#endif

#endif

